# Generated by Django 4.0.6 on 2022-08-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
                ('variacao_porcento', models.FloatField()),
                ('variacao', models.FloatField()),
                ('tendencia', models.CharField(max_length=100)),
                ('volume', models.FloatField()),
                ('volume_preco', models.FloatField()),
                ('valor', models.FloatField()),
                ('pl', models.FloatField()),
                ('eps', models.FloatField()),
                ('funcionarios', models.FloatField()),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
    ]
