# Generated by Django 4.0.6 on 2022-08-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletaAtivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColetaAtivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateTimeField(verbose_name='data publicada')),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('volume', models.FloatField()),
                ('high', models.FloatField()),
                ('close', models.FloatField()),
                ('adjclose', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ativos',
        ),
    ]
