# Generated by Django 4.0.6 on 2022-08-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coletaAtivos', '0002_coletaativos_delete_ativos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição Aqui')),
            ],
        ),
        migrations.RenameModel(
            old_name='ColetaAtivos',
            new_name='Precos',
        ),
    ]
